Repository EJComp-Unesp/Dvora-Frontend, pull requests merged in 2020-08, with the labels that each got.

#61 Feature/select board
  src/api/boards.js
  src/api/members.js
  src/components/boards/ModalBoard.js
  src/components/edits/MemberEdit.js
  src/components/edits/MemberEditForm.js
  src/components/registrations/MemberRegistrationForm.js
  src/views/dashboard/board/Board.js
  src/views/dashboard/team/Team.js
Labels: adjustment, enhancement

#69 Feature/settingsFix
  src/views/dashboard/settings/Settings.js
Labels: adjustment, enhancement

#68 Correções na tela de registro
  src/components/menus/Sidebar.js
  src/views/register/Registro.js
  src/views/register/styles/register.js
Labels: adjustment

#71 Adicionando icone de avatar do membro + correções de api
  src/api/feedback.js
  src/components/edits/MemberEditForm.js
  src/components/menus/Nav.js
  src/components/menus/TopNavbar.js
  src/components/menus/styles/menus.js
  src/components/monitorings/MemberList.js
  src/views/dashboard/Dashboard.js
  src/views/dashboard/routes.js
  src/views/dashboard/team/Team.js
Labels: adjustment

#75 Página de detalhes de acompanhamento
  src/api/feedback.js
  src/components/common/monitoring/DutyContainer.js
  src/components/monitorings/MonitoringHeader.js
  src/views/dashboard/monitoring/MonitoringDetails.js
Labels: enhancement

#82 verificação da validade do token
  src/api/auth.js
  src/views/login/Login.js
Labels: adjustment

#84 corrigindo bug no select da diretoria
  src/components/edits/MemberEditForm.js
  src/components/registrations/MemberRegistrationForm.js
Labels: adjustment, bug

#88 Mudança em alguns detalhes da aplicação
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/components/menus/TopNavbar.js
Labels: adjustment

#83 Alterações no forms de update
  src/components/edits/MemberEdit.js
  src/components/edits/MemberEditForm.js
  src/views/dashboard/team/Team.js
Labels: adjustment, bug
